ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'support_viewer';

DO $$
BEGIN
  CREATE TYPE "TenantStatus" AS ENUM ('ACTIVE', 'DELETING');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'UPDATE_INSTANCE';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'CREATE_USER';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'UPDATE_USER';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'DELETE_USER';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'RESET_USER_PASSWORD';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'DELETE_TENANT';
ALTER TYPE "OperationAction" ADD VALUE IF NOT EXISTS 'FORCE_DELETE_TENANT';

ALTER TABLE "tenants"
ADD COLUMN IF NOT EXISTS "status" "TenantStatus" NOT NULL DEFAULT 'ACTIVE';
