-- AlterEnum
ALTER TYPE "InstanceStatus" ADD VALUE IF NOT EXISTS 'STARTING';
ALTER TYPE "InstanceStatus" ADD VALUE IF NOT EXISTS 'STOPPING';
ALTER TYPE "InstanceStatus" ADD VALUE IF NOT EXISTS 'TERMINATING';
